### ISSUE TITLE
Run workflow and composite commands

### ISSUE THREAD

**Issue by rsenden** [fortify/fcli#1]
This issue holds ideas and proposals for running workflows and composite commands.

* Investigate possibility to run multiple subcommands in one go:
    * For example: `fcli login ssc --url ... get applications -o applications.json get versions -o versions.json logout ssc`
    * See picocli `subcommandsRepeatable = true` configuration option
* Allow shell-based chaining of commands by providing suitable output and functionality for parsing input; some examples:
    * `FCLI_FMT=json fcli create ssc version app/version … | fcli … --someOption=${{ stdin.json.project.id }}`
    * `for v in $(fcli get versions); do fcli download ssc artifact --from ${v}`

Idea for workflow syntax:

```yaml
# Define environment variables for use during workflow run, inheriting from parent environment
env:    
  name: value

# Should we have a separate element for logging in? This would open transient session and would auto-logout
# after workflow completion 
login:   
  ssc:
    url: ...

steps:
  - id: <id used for referencing output of this step in other steps>
    name: Name to display when running this step
    if: ${{ steps.previousStepId.output.json.criticalIssueCount > 0 }}
    forEach: ${{ steps.previousStepId.output.json.data[].id }}
    fcli: <fcli command to run>
    composite:
      async: true|false # Run each step in a separate thread, for example allowing to spawn both sast and dast scans
      maxThreads: 5   # Maximum number of threads to spawn
      joinThreads: true|false # If async==true, wait until all steps defined below have completed
      steps:
        - id, name, fcli, ...
```

Regarding the `fcli:` entry:
* Can use expressions like ${{ env.xyz }}, ${{ steps.abc.output.plain }}, ${{ steps.abc.output.json.someProperty}}, ...
* Can use `run cmd` subcommand to run arbitrary commands (`run cmd` should be disabled by default for security reasons, can be enabled through `fcli config run-cmd enabled true|false` or something similar
* Can use `run workflow` to run other workflows

**Comment by rsenden** [comment]
Note that the 'mentioned' above is incorrect; `#205` doesn't have anything to do this with this issue, but used `#1` to refer to a number list item.

**Comment by rsenden** [comment]
Potentially we could use an approach like the following for integrating workflows into fcli:

* Have an `fcli run <workflow> [workflow-options]` command for easy invocation, even though this doesn't really correspond to current fcli structure
* `<workflow>` would either be:
    * A built-in workflow
    * A custom workflow added through an `fcli config workflow add/import` command
    * Potentially, the name of a local file or even remote URL containing a workflow (but non-preconfigured workflows may be more difficult to handle when generating usage information; see below)
* Workflows are (for example) in yaml format, defining properties like listed below for defining workflow characteristics   

```
metadata:
  usage.header: 'My workflow'
  usage.description: 'Some description (maybe accept array of multiple description lines)'
  # usage.descriptionKey: ... (for built-in workflows, referencing resource bundle properties)
  options:
    - names:
      - long: myOption
      - short: o
    - description/descriptionKey: ...
    - required: true
    - interactive: true
    - ... (Other properties defined by picocli OptionSpec.Builder and ArgSpec.Builder

workflow:
  ...
```

Upon startup, fcli would load all predefined/pre-configured workflows, and/or the workflow file listed on the command line (if we can easily obtain this before picocli is actually being invoked), and use the yaml properties listed above to programmatically register each workflow as a sub-command on the `fcli run` command (see https://picocli.info/picocli-programmatic-api.html).

Now:
* If the user runs `fcli run` (without workflow) or `fcli run --help`, picocli would simply list all known workflows as sub-commands, including workflow description (from `usage.header` property). 
* If the user runs `fcli run fod-sast-scan -h`, picocli would display the the `fod-sast-scan` workflow usage header, synopsis, description, options, ..., all based on the information defined in the workflow definition

If we can easily identify which workflow is being requested, the process above can probably be optimized to only load that particular workflow, i.e. if `fcli run fod-sast-scan ...` is being invoked, we would only need to load the `fod-sast-scan` workflow. We'd only need to load all workflows if `fcli run` is invoked without workflow (or with unknown workflow), such that the usage information can display all known workflows as subcommands.
